create table accounts
(
    id             int8 generated by default as identity,
    balance        numeric(19, 2) not null,
    iban           varchar(255)   not null,
    name           varchar(255)   not null,
    status         varchar(255)   not null,
    client_id      int8           not null,
    credit_card_id int8,
    primary key (id)
)
create table clients
(
    id      int8 generated by default as identity,
    status  varchar(255) not null,
    user_id int8,
    primary key (id)
)
create table credit_cards
(
    id          int8 generated by default as identity,
    card_number varchar(255) not null,
    is_expired  boolean      not null,
    account_id  int8,
    primary key (id)
)
create table payments
(
    id            int8 generated by default as identity,
    amount        numeric(19, 2) not null,
    details       varchar(255),
    payment_date  date           not null,
    receiver_iban varchar(255)   not null,
    status        varchar(255)   not null,
    account_id    int8           not null,
    primary key (id)
)
create table requests
(
    id            int8 generated by default as identity,
    action_date   timestamp,
    creation_date timestamp not null,
    account_id    int8      not null,
    client_id     int8      not null,
    primary key (id)
)
create table users
(
    id        int8 generated by default as identity,
    email     varchar(255) not null,
    is_admin  boolean      not null,
    name      varchar(255) not null,
    password  varchar(255) not null,
    client_id int8,
    primary key (id)
)
create
index ACCOUNT_NAME_INDEX on accounts (name)
create
index PAYMENT_BALANCE_INDEX on accounts (balance)
alter table if exists credit_cards add constraint CARD_NUMBER_UNIQUE_CONSTRAINT unique (card_number)
create
index PAYMENT_DATE_INDEX on payments (payment_date)
create
index PAYMENT_ACCOUNT_INDEX on payments (account_id)
alter table if exists users add constraint EMAIL_UNIQUE_CONSTRAINT unique (email)
alter table if exists accounts add constraint FK_CLIENT foreign key (client_id) references clients
alter table if exists accounts add constraint FK_CREDIT_CARD foreign key (credit_card_id) references credit_cards
alter table if exists clients add constraint FK_USER_ID foreign key (user_id) references users
alter table if exists credit_cards add constraint FK_ACCOUNT_ID foreign key (account_id) references accounts
alter table if exists payments add constraint FK_PAYMENT_ACCOUNT foreign key (account_id) references accounts
alter table if exists requests add constraint FK_REQUEST_ACCOUNT foreign key (account_id) references accounts
alter table if exists requests add constraint FK_REQUEST_CLIENT foreign key (client_id) references clients
alter table if exists users add constraint FK_USER_CLIENT_ID foreign key (client_id) references clients
